### PR TITLE
use new owncloud package repo for centos, change tests and fix broken tests

### PR DESCRIPTION
**Pull request by BeneDicere**

### CODE REVIEW

**Comment by shoekstra** [comment]
Awesome stuff - will check integration tests tomorrow and merge if all good. :+1:

**Comment by shoekstra** [comment]
Safe to assume this also fixes #11?

**Comment by BeneDicere** [comment]
No, this does not touch selinux stuff.

**Comment by shoekstra** [comment]
Everything compiles and installs when running Beaker so looks good, thanks!

**Pull request merged**
