### PR TITLE
Raise range for epel dependency

### PR DESCRIPTION
**Pull request by AndreaGiardini**

### CODE REVIEW

**Comment by AndreaGiardini** [comment]
Please re-trigger the tests

**Comment by shoekstra** [comment]
Tests fail for Ruby 1.9.3 but passed for the rest.  Will check this out separately.

**Comment by AndreaGiardini** [comment]
Please release a new version, right now the range is too restrictive for a normal use

**Comment by shoekstra** [comment]
0.5.0 has been published.

**Pull request merged**
