### PR TITLE
Allowing more Apache SSL options to be tweaked

### PR DESCRIPTION
**Pull request by jgnagy**
Not a tremendous change here. Just passing through a few Apache SSL options to the underlying puppet-apache module. Allowing `ssl_cipher` and `ssl_protocol`. Updated the README and the CHANGELOG.

### CODE REVIEW

**Comment by shoekstra** [comment]
Awesome stuff!  Fix the tests and I'll merge with pleasure :+1:

**Comment by jgnagy** [comment]
I would be happy to fix any tests that I broke, but I'm not sure I can figure out how I broke it. It seems to be failing somewhere in lines 185 - 190 of https://github.com/jgnagy/puppet-owncloud/blob/feature/more_apache_ssl_options/spec/classes/owncloud_spec.rb related to this:

            [
              /<VirtualHost \*:80>/,
              /ServerName owncloud./
            ].each do |line|
              is_expected.to contain_file('/var/lib/puppet/concat/25-owncloud-http.conf/fragments/0_owncloud-http-apache-header').with_content(line)
            end

I can't see how the changes I made changed this at all. I will admit that I could use some help. Could this instead be related to an upstream change from the apache puppet module?

**Comment by shoekstra** [comment]
Agreed - I'll take a look later and let you know what I find.

**Comment by jgnagy** [comment]
_sigh_, I'm not sure why your tests with `STRICT_VARIABLES=yes` don't like me, but I can assure you that my changes should have nothing to do with `Undefined variable "::is_maj_version"` for CentOS things, which is where this is now failing. I'm not ashamed to admit that I could use some help, and I'm tempted to just create a new branch and try applying my changes again if this doesn't go away. I can say that I'm using this, in production, with no ill effects.

**Comment by shoekstra** [comment]
Will take a look this weekend to fix the errors, thanks!

**Pull request merged**
