### PR TITLE
Fix centos support

### PR DESCRIPTION
**Pull request by AndreaGiardini**
Installation on CentOS is broken due to a typo

### CODE REVIEW

**Comment by shoekstra** [comment]
Wow, loving this. Will take a look now to see why tests are failing (including your PR).

**Comment by AndreaGiardini** [comment]
Please release a new version with the current development branch

**Comment by shoekstra** [comment]
Hi,

Will release it when I am home this evening.

**Comment by shoekstra** [comment]
0.4.3 has been release to forge. Please open a new issue if you experience any problems with it.

**Pull request closed without merging**
