### PR TITLE
Install owncloud-server instead of owncloud (remove apache dependency)

### PR DESCRIPTION
**Pull request by AndreaGiardini**
The package `owncloud` depends on apache. Since i want to use this module with nginx i am supposed to write in my manifest:

```
class { '::owncloud':
  manage_apache => false,
  manage_vhost  => false,
  datadirectory => '/var/www/cloud.myprecise.box',
  db_host => 'localhost',
  db_name => 'owncloud',
  db_user => 'owncloud',
  db_pass => 'p4ssw0rd',
}
```

What i get is a non-working machine since nginx and apache compete to bind on the 80 port. The solution is to replace the `owncloud` package with `owncloud-server` (no apache dep)

### CODE REVIEW

**Comment by AndreaGiardini** [comment]
Updates?

**Comment by AndreaGiardini** [comment]
Can you please merge/review this? Thanks

**Comment by shoekstra** [comment]
Looks good!

Sorry for the delay, have been crazy busy last few weeks and don't work that much with Puppet anymore.

**Comment by AndreaGiardini** [comment]
Can you please release a new version on puppetforge? The module is broken for me since i need to configure owncloud using nginx

**Comment by shoekstra** [comment]
0.4.2 has been released to the Forge.

**Comment by AndreaGiardini** [comment]
Well... Have a look at #24 because CentOS support is now broken

**Pull request merged**
