### PR TITLE
Pin apt and concat modules to make rspec green

### PR DESCRIPTION
**Pull request by guimaluf**

### CODE REVIEW

**Comment by shoekstra** [comment]
What was failing that you want it to pin the git repos?  All tests are [passing](https://travis-ci.org/shoekstra/puppet-owncloud/builds/56132440) for the v0.4.0 release.

**Comment by guimaluf** [comment]
The new version of concat and apt modules was generating error/failure in every rspec run, after pinning their version I could get a green run. Since travis is passing you should ignore this PR.

**Comment by shoekstra** [comment]
I'll pull the latest versions and test tomorrow. If I can't replicate the problem I'll close this issue, otherwise will see how it can be resolved.

**Comment by shoekstra** [comment]
Pinning versions in the `.fixtures.yml` is just a bad idea, will work to incorporate changes in shoekstra/puppet-owncloud#13 rather than this.

**Pull request closed without merging**
