### PR TITLE
Ssl support example

### PR DESCRIPTION
**Pull request by ikke-t**
Hi,

thanks for your module. I don't dare to run my stuff without SSL, so I added the vhost_https part.

The ssl certs part could be changed to variables, to make it possible to push them via hiera.

Please have a look.

### CODE REVIEW

**Comment by shoekstra** [comment]
Hey there,

I already had some SSL related stuff done, so will complete shortly and publish it to the forge.

The module isn't able to do SSL itself at the moment, but you are able to use `manage_vhost => false` and then install your own vhost using the `apache::vhost` define in the meanwhile.

You mentioned config file permissions are broken in [this commit](https://github.com/ikke-t/puppet-owncloud/commit/18ae31f41b56d2790fb623bfeddd64c6567e0998), what error are you seeing?  I haven't had any problems myself relating to file permissions.

Cheers,

**Comment by ikke-t** [comment]
Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-39-generic x86_64)

**Comment by shoekstra** [comment]
I can't seem to replicate your permissions problem.  Created a Vagrant box running Trusty and all looks to be as expected.

Ubuntu version:

```
root@www1:/var/www/owncloud/config# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:        14.04
Codename:       trusty
```

Before creating admin user:

```
root@www1:/var/www/owncloud/config# ls -l
total 32
-rw-r--r-- 1 www-data www-data   265 Jan 10 04:38 autoconfig.php
-rw-rw-r-- 1 www-data www-data 24903 Dec  8 10:34 config.sample.php
```

After creating admin user:

```
root@www1:/var/www/owncloud/config# ls -l
total 32
-rw-r----- 1 www-data www-data   615 Jan 10 04:42 config.php
-rw-rw-r-- 1 www-data www-data 24903 Dec  8 10:34 config.sample.php
```

**Comment by ikke-t** [comment]
ok, good that you proved it wrong. I don't remember why it was so. I recall I couldn't configure it, and noticed from logs that it couldn't write to config.php. That's how I corrected it, but I don't remember why it ended up into such state. I played around quite much with the module and installation, rerunning it several times, until it all worked. Maybe there was some leftover files from that. False alarm then.

**Comment by shoekstra** [comment]
The only thing I can think of is that something else is setting the file permission in your environment.  This module doesn't enforce file ownership on files such as config.php or the user data directories so if something else changes file ownership, the module won't reset them to what they should be for ownCloud to work properly.

I've added SSL support and uploaded a new version of the module to the forge (0.2.0).  Give this a go and let me know if you still have an issue.

**Pull request closed without merging**
