### PR TITLE
update debian/ubuntu repository

### PR DESCRIPTION
**Pull request by project0**

### CODE REVIEW

**Comment by project0** [comment]
spec test seems to be broken on upstream with strict variable on ::remi class.

**Comment by shoekstra** [comment]
Ahh that remi module.. I'm going to fix that now and will merge this in a bit 👍

**Comment by project0** [comment]
@shoekstra centos6 is still failing after upstream merge

**Comment by shoekstra** [comment]
I've got some time off at the moment so will take a proper look. Going to refactor a bit since ownCloud changed how they package the app.

**Comment by shoekstra** [comment]
Have stopped using the `remi` module so the pain it brought is now gone for good.  I had already started on supporting ownCloud, so applied my local changes to update the repos which means this PR is no longer needed.

I'll push a new version to the forge shortly.

**Pull request closed without merging**
